import { ProjectType } from "../types"

export const projects: ProjectType[] = [
	{
		url: "mid-century-revisited",
		name: "Mid Century Revisited",
		text: "mid-century-revisited.md",
		photos: [
			"https://i.ibb.co/5GDkf4b/SR17245983-20-1.jpg",
			"https://i.ibb.co/KVJMd86/SR17245983-25-1.jpg",
			"https://i.ibb.co/BnBqnXx/SR17245983-29-1.jpg",
			"https://i.ibb.co/jzfcBQr/SR17245983-31-1.jpg",
			"https://i.ibb.co/D1TcHJB/SR17245983-32-1.jpg",
			"https://i.ibb.co/RyR3Qfq/SR17245983-34-1.jpg",
			"https://i.ibb.co/860N5tS/SR17245983-37-1.jpg",
			"https://i.ibb.co/mJyPyDm/SR17245983-38-1.jpg",
			"https://i.ibb.co/WNXw93G/SR17245983-48-1.jpg",
			"https://i.ibb.co/P9TxvKs/SR17245983-53-1.jpg",
			"https://i.ibb.co/h19NbD1/SR17245983-55-1.jpg",
			"https://i.ibb.co/G77Zh5F/SR17245983-56-1.jpg",
			"https://i.ibb.co/ZBvGVSK/SR17245983-58-1.jpg",
			"https://i.ibb.co/ThgPC9k/SR17245983-60-1.jpg",
			"https://i.ibb.co/HdxRMWk/SR17245983-68-1.jpg",
			"https://i.ibb.co/DCh73F5/SR17245983-70-1.jpg",
		],
		address: "Studio City, CA",
		team: [
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
			{
				name: "Daniel Elenes",
				role: "Project Lead",
			},
		],
		category: "multi",
	},
	{
		url: "the-traditional-shingle",
		name: "The Traditional Shingle",
		text: "the-traditional-shingle.md",
		photos: [
			"https://i.ibb.co/bRbFRqH/Carmar-1.jpg",
			"https://i.ibb.co/Jmxr61T/Carmar-2.jpg",
			"https://i.ibb.co/PY8Q6v0/Carmar-3.jpg",
			"https://i.ibb.co/Gnxb8j1/carmar-4.jpg",
			"https://i.ibb.co/1bkyRFQ/carmar-5.jpg",
			"https://i.ibb.co/BVc84jj/carmar-6.jpg",
			"https://i.ibb.co/809qJ71/carmar-7.jpg",
			"https://i.ibb.co/Db0ywPy/carmar-8.jpg",
			"https://i.ibb.co/NNX1T6q/carmar-9.jpg",
			"https://i.ibb.co/qRshSYS/carmar-10.jpg",
			"https://i.ibb.co/3h7YC4H/carmar-11.jpg",
			"https://i.ibb.co/xLgMYnk/carmar-12.jpg",
			"https://i.ibb.co/23d77Q3/carmar-13.jpg",
			"https://i.ibb.co/DWDm8r6/carmar-14.jpg",
			"https://i.ibb.co/1K1TfJ1/carmar-before-1.jpg",
			"https://i.ibb.co/k2zLH16/carmar-before-2.jpg",
			"https://i.ibb.co/FBM8dYc/carmar-before-3.jpg",
			"https://i.ibb.co/LpTyX68/carmar-before-4.jpg",
			"https://i.ibb.co/gMJ037d/carmar-before-5.jpg",
			"https://i.ibb.co/0qPwBjf/carmar-before-6.jpg",
		],
		address: "Hollywood Hills, CA",
		team: [
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
			{
				name: "Susan Mollasalehi",
				role: "Project Lead",
			},
		],
		category: "single",
	},
	{
		url: "spanish-revival",
		name: "Spanish Revival",
		text: "spanish-revival.md",
		photos: [
			"https://i.ibb.co/L8SgDMj/Copy-of-Koman-Kit2.jpg",
			"https://i.ibb.co/nfwXbqz/Koman-Din1.jpg",
			"https://i.ibb.co/ykpcMD8/Koman-Entry.jpg",
			"https://i.ibb.co/C7mzS3N/Koman-Entry2.jpg",
			"https://i.ibb.co/HKdjWQr/Koman-Front1.jpg",
			"https://i.ibb.co/fGV41SP/Koman-Hall.jpg",
			"https://i.ibb.co/XFJQghP/Koman-Kit1.jpg",
			"https://i.ibb.co/LN1GS4v/Koman-Kit3.jpg",
			"https://i.ibb.co/QcWFyJW/Koman-Liv1.jpg",
			"https://i.ibb.co/3rdJLxF/Koman-Liv3.jpg",
			"https://i.ibb.co/qpfyJVC/Koman-Patio.jpg",
			"https://i.ibb.co/f44xCbB/Koman-Patio2.jpg",
			"https://i.ibb.co/cvBb71n/Koman-Rear.jpg",
			"https://i.ibb.co/cgL4cr7/Koman-Shower.jpg",
			"https://i.ibb.co/2nXRCnc/Side-1.jpg",
			"https://i.ibb.co/J5mX1b0/spanish13.jpg",
		],
		address: "Rancho Santa Fe, CA",
		team: [
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
			{
				name: "Fabiola Tejeda",
				role: "Project Lead",
			},
			{
				name: "Roy Martinez",
				role: "Interior Design Principal",
			},
		],
		category: "retail",
	},
	{
		url: "the-modern-barn",
		name: "The Modern Barn",
		text: "the-modern-barn.md",
		photos: [
			"https://i.ibb.co/2tQWhyr/ADU-1.jpg",
			"https://i.ibb.co/7jG64ZP/Bathroom-1.jpg",
			"https://i.ibb.co/1J0QTcM/Bathroom-2.jpg",
			"https://i.ibb.co/M5hzsTp/Bedroom-1.jpg",
			"https://i.ibb.co/N9Nz6Jn/DJI-0026.jpg",
			"https://i.ibb.co/319wywD/DJI-0027.jpg",
			"https://i.ibb.co/XWGyW15/DJI-0028.jpg",
			"https://i.ibb.co/r0CZ1Jc/DJI-0029.jpg",
			"https://i.ibb.co/z28Rz0N/DJI-0030.jpg",
			"https://i.ibb.co/kD0pXNr/DJI-0031.jpg",
			"https://i.ibb.co/vZyJfg2/DJI-0032.jpg",
			"https://i.ibb.co/vhnSwZD/DJI-0033.jpg",
			"https://i.ibb.co/6XbKPQP/DJI-0034.jpg",
			"https://i.ibb.co/W0wc3hj/DJI-0035.jpg",
			"https://i.ibb.co/r3Zh0Bt/DJI-0036.jpg",
			"https://i.ibb.co/nfJ6T8v/DJI-0037.jpg",
			"https://i.ibb.co/DVhwtCL/Doorway-1.jpg",
			"https://i.ibb.co/48nr9vy/doorway-2.jpg",
			"https://i.ibb.co/SX3bDNs/FOH-1.jpg",
			"https://i.ibb.co/zVxmKzM/Kitchen-1.jpg",
			"https://i.ibb.co/2dLNvzr/Kitchen-2.jpg",
			"https://i.ibb.co/VTcZ9vJ/Kitchen-3.jpg",
			"https://i.ibb.co/1nnw38r/Living-Room-1.jpg",
			"https://i.ibb.co/PQVrjcY/Living-Room-2.jpg",
			"https://i.ibb.co/rs4vBJK/Master-Bath-1.jpg",
			"https://i.ibb.co/9snNnkC/Master-Bath-2.jpg",
			"https://i.ibb.co/HB60NyM/Master-Bath-3.jpg",
			"https://i.ibb.co/ssXgjBy/Outdoor-Grill.jpg",
			"https://i.ibb.co/8dP9BMV/Patio-1.jpg",
			"https://i.ibb.co/Q8jXxsn/The-View.jpg",
		],
		address: "Triunfo Canyon, CA",
		team: [
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
			{
				name: "Brian Asis",
				role: "Project Lead/Designer",
			},
		],
		category: "single",
	},
	{
		url: "the-california-classic",
		name: "The California Classic",
		text: "",
		photos: [
			"https://i.ibb.co/VNk18pb/california-classic.jpg",
			"https://i.ibb.co/hCmzT3T/San-Vicente-Day-View-2-09-29-2022.jpg",
			"https://i.ibb.co/gPHsFTM/San-Vicente-Day-View-4-09-29-2022.jpg",
			"https://i.ibb.co/5s1jKbR/San-Vicente-Day-View-1-09-29-2022.jpg",
			"https://i.ibb.co/vsz92s8/San-Vicente-Day-View-5-09-29-2022.jpg",
			"https://i.ibb.co/t3n1zGd/SV-Night-1.jpg",
			"https://i.ibb.co/pyLDwPY/SV-Night-2.jpg",
		],
		address: "Brentwood, CA (Under Construction)",
		team: [],
		category: "multi",
	},
	{
		url: "a-piece-of-craftmanship",
		name: "A Piece of Craftmanship",
		text: "a-piece-of-craftmanship.md",
		photos: [
			"https://i.ibb.co/7rwPx1k/DSC-0002.jpg",
			"https://i.ibb.co/LJrZf05/DSC-0006.jpg",
			"https://i.ibb.co/BjTsBxW/DSC-0052.jpg",
			"https://i.ibb.co/zSYxBfH/DSC-0055.jpg",
			"https://i.ibb.co/C5nGM1M/DSC-0321.jpg",
			"https://i.ibb.co/qC83D7K/DSC-0326.jpg",
			"https://i.ibb.co/jyxMwW3/Michigan1982.jpg",
		],
		address: "Pasadena, CA",
		team: [
			{
				name: "Doy L Cruz",
				role: "Project Lead",
			},
			{
				name: "Brian Asis",
				role: "Project Designer",
			},
			{
				name: "Brian Asis",
				role: "Project Lead/Designer",
			},
		],
		category: "retail",
	},
	{
		url: "the-french-mansard",
		name: "The French Mansard",
		text: "the-french-mansard.md",
		photos: [
			"https://i.ibb.co/GJcTRVK/1.jpg",
			"https://i.ibb.co/7tpL62w/2.jpg",
			"https://i.ibb.co/g9yQR6q/3.jpg",
			"https://i.ibb.co/tqGhQ2J/IS2zf67k3m0pen1000000000.jpg",
			"https://i.ibb.co/Nms7HZf/IS6eavb3qr7mdn1000000000.jpg",
			"https://i.ibb.co/b6hKQZT/IS23j7dt6o4bdn1000000000.jpg",
			"https://i.ibb.co/r77X0VG/ISa5iipq7u8men1000000000.jpg",
			"https://i.ibb.co/YjLP2vW/ISa9ljvzawc8dn1000000000.jpg",
			"https://i.ibb.co/mS3LY8L/ISap1jad9vaxdn1000000000.jpg",
			"https://i.ibb.co/xmqLzFK/ISe4s8t8e416881000000000.jpg",
			"https://i.ibb.co/q0HfL5G/ISekc7u9uzfjdn1000000000.jpg",
			"https://i.ibb.co/8YKQwYm/ISqlp7wcjct2dn1000000000.jpg",
			"https://i.ibb.co/Pzv05J3/ISucxu901fu2en1000000000.jpg",
			"https://i.ibb.co/K05356P/ISusduodzdsren1000000000.jpg",
			"https://i.ibb.co/Bwzdc7s/ISuwgvum2gwddn1000000000.jpg",
			"https://i.ibb.co/0X6pFyv/ISy78jtwljzodn1000000000.jpg",
		],
		address: "Nichols Canyon, CA",
		team: [
			{
				name: "Joshua Navarette",
				role: "Project Lead",
			},
			{
				name: "Brian Asis",
				role: "Project Designer",
			},
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
		],
		category: "single",
	},
	{
		url: "a-montecito-classic",
		name: "A Montecito Classic",
		text: "a-montecito-classic.md",
		photos: [
			"https://i.ibb.co/r02jpmQ/Backyard-View.jpg",
			"https://i.ibb.co/3B23T3G/Balcony-1.jpg",
			"https://i.ibb.co/mrKZxcW/Cieling-Fixture-1.jpg",
			"https://i.ibb.co/rZzd8Tq/Cieling-Fixture-2.jpg",
			"https://i.ibb.co/dr9fYdt/Dining-to-Front-Door.jpg",
			"https://i.ibb.co/sysvFCg/Driveway-1.jpg",
			"https://i.ibb.co/tJ3k7zc/Front-Of-House-1.jpg",
			"https://i.ibb.co/bL0bxsh/Front-of-House-2.jpg",
			"https://i.ibb.co/j6GJDzZ/Front-of-House-3.jpg",
			"https://i.ibb.co/kB5nRR9/Front-of-House-4.jpg",
			"https://i.ibb.co/1m67t1N/Hallway-Dining.jpg",
			"https://i.ibb.co/bH7LQbK/House-Stairs-1.jpg",
			"https://i.ibb.co/NxW2jmT/Kitchen-1.jpg",
			"https://i.ibb.co/1L1jKy4/Kitchen-2.jpg",
			"https://i.ibb.co/pRc9LXr/Kitchen-Nook-1.jpg",
			"https://i.ibb.co/r6LNdHM/Kitchen-Nook-2.jpg",
			"https://i.ibb.co/DKWWktD/Landscaping-2.jpg",
			"https://i.ibb.co/44Wzbkd/Landscaping.jpg",
			"https://i.ibb.co/R32kxRW/Living-Room-1.jpg",
			"https://i.ibb.co/w7gXd4W/Media-Bathroom.jpg",
			"https://i.ibb.co/TR4LLMQ/Media-Room-1.jpg",
			"https://i.ibb.co/74Gj8FN/Media-Room-2.jpg",
			"https://i.ibb.co/nsn6HZk/Office-1.jpg",
			"https://i.ibb.co/HqVRt0N/Office-Window.jpg",
			"https://i.ibb.co/7JPzRq1/Patio-1.jpg",
			"https://i.ibb.co/mHQQ5Hp/Patio-2.jpg",
			"https://i.ibb.co/CbZ3y2b/Patio-3.jpg",
			"https://i.ibb.co/fVWLb7K/pool.jpg",
			"https://i.ibb.co/1qK31Nm/Staircase-1.jpg",
			"https://i.ibb.co/3C5cm5q/staircase-2.jpg",
			"https://i.ibb.co/bbNYd99/Staircase-3.jpg",
			"https://i.ibb.co/nLgph9t/Staircase-Top.jpg",
			"https://i.ibb.co/k1NkZ1X/Window-1.jpg",
			"https://i.ibb.co/S07YQ6q/Window-2.jpg",
			"https://i.ibb.co/Zdw6BG8/Window-3.jpg",
		],
		address: "Beverly Hills, CA",
		team: [
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
			{
				name: "Alma Chamanara",
				role: "Project Designer",
			},
		],
		category: "retail",
	},
	{
		url: "the-bernadus-ranch-house",
		name: "The Bernadus Branch House",
		text: "",
		photos: [
			"https://i.ibb.co/LSGj9X6/Rancho-Palo-Verdes-Craig-House-1-of-62.jpg",
			"https://i.ibb.co/M5dFZRy/Rancho-Palo-Verdes-Craig-House-2-of-62.jpg",
			"https://i.ibb.co/Fs0MSX5/Rancho-Palo-Verdes-Craig-House-3-of-62.jpg",
			"https://i.ibb.co/c624Jbz/Rancho-Palo-Verdes-Craig-House-5-of-62.jpg",
			"https://i.ibb.co/L6WWSLR/Rancho-Palo-Verdes-Craig-House-6-of-62.jpg",
			"https://i.ibb.co/qBLYBtP/Rancho-Palo-Verdes-Craig-House-7-of-62.jpg",
			"https://i.ibb.co/DC8CHDC/Rancho-Palo-Verdes-Craig-House-8-of-62.jpg",
			"https://i.ibb.co/zSXgcTV/Rancho-Palo-Verdes-Craig-House-9-of-62.jpg",
			"https://i.ibb.co/vv1xGxL/Rancho-Palo-Verdes-Craig-House-10-of-62.jpg",
			"https://i.ibb.co/1XwKk9N/Rancho-Palo-Verdes-Craig-House-11-of-62.jpg",
			"https://i.ibb.co/FDZyD1V/Rancho-Palo-Verdes-Craig-House-12-of-62.jpg",
			"https://i.ibb.co/vkjfd3b/Rancho-Palo-Verdes-Craig-House-13-of-62.jpg",
			"https://i.ibb.co/G2bgCwM/Rancho-Palo-Verdes-Craig-House-14-of-62.jpg",
			"https://i.ibb.co/KVkFK2Y/Rancho-Palo-Verdes-Craig-House-15-of-62.jpg",
			"https://i.ibb.co/JqR6rpD/Rancho-Palo-Verdes-Craig-House-16-of-62.jpg",
			"https://i.ibb.co/7CMLK2R/Rancho-Palo-Verdes-Craig-House-17-of-62.jpg",
			"https://i.ibb.co/Rvm9D4Z/Rancho-Palo-Verdes-Craig-House-18-of-62.jpg",
			"https://i.ibb.co/BrhwVrv/Rancho-Palo-Verdes-Craig-House-19-of-62.jpg",
			"https://i.ibb.co/MhFV6jx/Rancho-Palo-Verdes-Craig-House-20-of-62.jpg",
			"https://i.ibb.co/n8SYXb0/Rancho-Palo-Verdes-Craig-House-21-of-62.jpg",
			"https://i.ibb.co/ChQngKj/Rancho-Palo-Verdes-Craig-House-22-of-62.jpg",
			"https://i.ibb.co/wz8wkpD/Rancho-Palo-Verdes-Craig-House-23-of-62.jpg",
			"https://i.ibb.co/thpP0Kk/Rancho-Palo-Verdes-Craig-House-24-of-62.jpg",
			"https://i.ibb.co/Kzk2S6J/Rancho-Palo-Verdes-Craig-House-25-of-62.jpg",
			"https://i.ibb.co/nP0WSDM/Rancho-Palo-Verdes-Craig-House-26-of-62.jpg",
			"https://i.ibb.co/r6kLhJS/Rancho-Palo-Verdes-Craig-House-27-of-62.jpg",
			"https://i.ibb.co/KmYW2SQ/Rancho-Palo-Verdes-Craig-House-28-of-62.jpg",
			"https://i.ibb.co/2WdN6gq/Rancho-Palo-Verdes-Craig-House-29-of-62.jpg",
			"https://i.ibb.co/Ns5dZr6/Rancho-Palo-Verdes-Craig-House-30-of-62.jpg",
			"https://i.ibb.co/jkTVPtN/Rancho-Palo-Verdes-Craig-House-31-of-62.jpg",
			"https://i.ibb.co/VqSnPvg/Rancho-Palo-Verdes-Craig-House-32-of-62.jpg",
			"https://i.ibb.co/6XFSmdS/Rancho-Palo-Verdes-Craig-House-33-of-62.jpg",
			"https://i.ibb.co/vh4Tc8c/Rancho-Palo-Verdes-Craig-House-34-of-62.jpg",
			"https://i.ibb.co/qYM5fyG/Rancho-Palo-Verdes-Craig-House-35-of-62.jpg",
			"https://i.ibb.co/vBDm257/Rancho-Palo-Verdes-Craig-House-36-of-62.jpg",
			"https://i.ibb.co/2YcQwdq/Rancho-Palo-Verdes-Craig-House-37-of-62.jpg",
			"https://i.ibb.co/xGhMcS0/Rancho-Palo-Verdes-Craig-House-38-of-62.jpg",
			"https://i.ibb.co/F0Cw0KW/Rancho-Palo-Verdes-Craig-House-39-of-62.jpg",
			"https://i.ibb.co/McLgJJM/Rancho-Palo-Verdes-Craig-House-40-of-62.jpg",
			"https://i.ibb.co/6sDKYHZ/Rancho-Palo-Verdes-Craig-House-41-of-62.jpg",
			"https://i.ibb.co/dGMr507/Rancho-Palo-Verdes-Craig-House-42-of-62.jpg",
			"https://i.ibb.co/4g2pxGS/Rancho-Palo-Verdes-Craig-House-43-of-62.jpg",
			"https://i.ibb.co/dKFvy4X/Rancho-Palo-Verdes-Craig-House-44-of-62.jpg",
			"https://i.ibb.co/Jqm9b4X/Rancho-Palo-Verdes-Craig-House-45-of-62.jpg",
			"https://i.ibb.co/j4qZfJB/Rancho-Palo-Verdes-Craig-House-46-of-62.jpg",
			"https://i.ibb.co/JkQmyh3/Rancho-Palo-Verdes-Craig-House-47-of-62.jpg",
			"https://i.ibb.co/R0XDPGB/Rancho-Palo-Verdes-Craig-House-48-of-62.jpg",
			"https://i.ibb.co/XCntWgR/Rancho-Palo-Verdes-Craig-House-49-of-62.jpg",
			"https://i.ibb.co/ngD7mgN/Rancho-Palo-Verdes-Craig-House-50-of-62.jpg",
			"https://i.ibb.co/KKHmbkL/Rancho-Palo-Verdes-Craig-House-51-of-62.jpg",
			"https://i.ibb.co/VjY3c1x/Rancho-Palo-Verdes-Craig-House-52-of-62.jpg",
			"https://i.ibb.co/CtckDGW/Rancho-Palo-Verdes-Craig-House-53-of-62.jpg",
			"https://i.ibb.co/8XSCNB9/Rancho-Palo-Verdes-Craig-House-54-of-62.jpg",
			"https://i.ibb.co/g3b4RZw/Rancho-Palo-Verdes-Craig-House-55-of-62.jpg",
			"https://i.ibb.co/K5RLC18/Rancho-Palo-Verdes-Craig-House-56-of-62.jpg",
			"https://i.ibb.co/LpzG4G2/Rancho-Palo-Verdes-Craig-House-57-of-62.jpg",
			"https://i.ibb.co/yYCthx3/Rancho-Palo-Verdes-Craig-House-58-of-62.jpg",
			"https://i.ibb.co/TkZHxGx/Rancho-Palo-Verdes-Craig-House-59-of-62.jpg",
			"https://i.ibb.co/LNQgXn3/Rancho-Palo-Verdes-Craig-House-60-of-62.jpg",
			"https://i.ibb.co/ts4grRL/Rancho-Palo-Verdes-Craig-House-61-of-62.jpg",
			"https://i.ibb.co/Hn5ymzg/Rancho-Palo-Verdes-Craig-House-62-of-62.jpg",
			"https://i.ibb.co/HBtzjs7/Rancho-Palo-Verdes-Drone-Shots-1-of-5.jpg",
			"https://i.ibb.co/60nM0p3/Rancho-Palo-Verdes-Drone-Shots-2-of-5.jpg",
			"https://i.ibb.co/4KRFbY9/Rancho-Palo-Verdes-Drone-Shots-3-of-5.jpg",
			"https://i.ibb.co/G2TR9Bb/Rancho-Palo-Verdes-Drone-Shots-4-of-5.jpg",
			"https://i.ibb.co/y6yNSgL/Rancho-Palo-Verdes-Drone-Shots-5-of-5.jpg",
		],
		address: "Rancho Palos Verda, CA",
		team: [
			{
				name: "K. Jake Yalong",
				role: "Structural Design Lead",
			},
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
		],
		category: "multi",
	},
	{
		url: "the-seamless-adu",
		name: "The Seamless ADU",
		text: "the-seamless-adu.md",
		photos: [
			"https://i.ibb.co/pJjpnKh/Front-Door.jpg",
			"https://i.ibb.co/Z2qYjmy/Interior-Side-Wide.jpg",
			"https://i.ibb.co/PD3Kwnz/Interior-Side.jpg",
			"https://i.ibb.co/sv06TRN/outside-1.jpg",
			"https://i.ibb.co/K55sLWn/Outside-2.jpg",
			"https://i.ibb.co/Tw0PPnH/Outside-3.jpg",
		],
		address: "Calabasas, CA",
		team: [
			{
				name: "K. Jake Yalong",
				role: "Structural Design Lead",
			},
			{
				name: "Joshua Navarette",
				role: "Project Designer",
			},
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
		],
		category: "multi",
	},
	{
		url: "the-cyclist",
		name: "The Cyclist",
		text: "the-cyclist.md",
		photos: [
			"https://i.ibb.co/vYpTtwL/Backyard-1.jpg",
			"https://i.ibb.co/R6ZpqxT/backyard-2.jpg",
			"https://i.ibb.co/QNHdj3c/backyard-3.jpg",
			"https://i.ibb.co/xXXtqCN/backyard-4.jpg",
			"https://i.ibb.co/h2XHJDm/backyard-5.jpg",
			"https://i.ibb.co/5W4d6Mf/backyard-texture.jpg",
			"https://i.ibb.co/t4bTDt4/backyard6.jpg",
			"https://i.ibb.co/vPwf4SH/backyard6-min.jpg",
			"https://i.ibb.co/Sf8fKgD/bathroom-1.jpg",
			"https://i.ibb.co/HTx0Vg2/bathroom-2.jpg",
			"https://i.ibb.co/WgG7mPf/bathroom-3.jpg",
			"https://i.ibb.co/HTrsgZQ/bathroom-4.jpg",
			"https://i.ibb.co/hY4YB6D/bathroom-6.jpg",
			"https://i.ibb.co/9T23Lz3/bathroom-7.jpg",
			"https://i.ibb.co/YRKgYFD/bookshelf.jpg",
			"https://i.ibb.co/PZSyQK7/Car-Port.jpg",
			"https://i.ibb.co/P686sFk/Driveway.jpg",
			"https://i.ibb.co/SPtsyLn/FOH-1.jpg",
			"https://i.ibb.co/CJJLgcC/FOH-2.jpg",
			"https://i.ibb.co/9hkHzmd/foh-plants.jpg",
			"https://i.ibb.co/cr2Dhzm/Front-Door.jpg",
			"https://i.ibb.co/fq9cFRc/open-room-1.jpg",
			"https://i.ibb.co/rxf9Vr8/open-room-1-min.jpg",
			"https://i.ibb.co/KGPcH8P/open-room-2.jpg",
			"https://i.ibb.co/rtKFws7/open-room-3.jpg",
			"https://i.ibb.co/fNNG4QL/open-room-4.jpg",
			"https://i.ibb.co/wpX6Wxf/open-room-4-min.jpg",
		],
		address: "Reseda, California, CA",
		team: [
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
			{
				name: "Jevon Carrington",
				role: "Project Architect/Designer",
			},
		],
		category: "single",
	},
	{
		url: "the-toscana-influence",
		name: "The Toscana Influence",
		text: "the-toscana-influence.md",
		photos: [
			"https://i.ibb.co/NsN2Gsk/908-Front1.jpg",
			"https://i.ibb.co/LNYCX50/Front-Pers-B.jpg",
			"https://i.ibb.co/gD4scfg/Front-Pers-C.jpg",
			"https://i.ibb.co/ftzdMKX/glen-004.jpg",
			"https://i.ibb.co/Nx2rGJH/glen-015.jpg",
			"https://i.ibb.co/xFYhm1W/glen-033.jpg",
			"https://i.ibb.co/8rf2YJC/glen-035.jpg",
			"https://i.ibb.co/2NdRdRv/glen-043.jpg",
			"https://i.ibb.co/4KhhYQ7/glen-044.jpg",
			"https://i.ibb.co/wNC5QJG/glen-051.jpg",
			"https://i.ibb.co/XVYtxY1/glen-052.jpg",
			"https://i.ibb.co/L0MSMJ0/glen-055.jpg",
			"https://i.ibb.co/h9Kbr4m/glen-060.jpg",
			"https://i.ibb.co/jHJ3xqG/glen-064.jpg",
			"https://i.ibb.co/2qSNwNm/Shower-208.jpg",
		],
		address: "Culver City, CA",
		team: [
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
		],
		category: "retail",
	},
	{
		url: "the-music-barn",
		name: "The Music Barn (Rendering)",
		text: "the-music-barn.md",
		photos: [
			"https://i.ibb.co/j4mXHwP/Michigan-Exterior-1.jpg",
			"https://i.ibb.co/KFFqDfH/Michigan-Exterior-2.jpg",
			"https://i.ibb.co/9bK0tV1/Michigan-Exterior-3.jpg",
			"https://i.ibb.co/8xv6d4k/Michigan-Exterior-4.jpg",
			"https://i.ibb.co/Ycm4gMv/Michigan-Exterior-5.jpg",
			"https://i.ibb.co/VBydsLJ/Michigan-Interior-1.jpg",
			"https://i.ibb.co/pjzt6Gg/Michigan-Interior-2.jpg",
			"https://i.ibb.co/rwBg2PM/Michigan-Interior-3.jpg",
			"https://i.ibb.co/2SxMsX3/Michigan-Interior-4.jpg",
			"https://i.ibb.co/z2rFVnF/Michigan-Interior-5.jpg",
		],
		address: "Mullet Lake, Michigan",
		team: [],
		category: "multi",
	},
	{
		url: "the-andalusian",
		name: "The Andalusian (Rendering)",
		text: "",
		photos: [
			"https://i.ibb.co/xSYvzPC/longden-front-08-01-2021.jpg",
			"https://i.ibb.co/ZmRqcd3/longden-view2-08-01-2021.jpg",
			"https://i.ibb.co/gPWW42P/longden-view3-08-01-2021.jpg",
		],
		address: "",
		team: [],
		category: "single",
	},
	{
		url: "the-framicist",
		name: "The Framicist (Rendering)",
		text: "",
		photos: ["https://i.ibb.co/d7b2z0f/mulholland-front1-1.jpg", "https://i.ibb.co/k1ZJXyG/mulholland-front2.jpg"],
		address: "",
		team: [],
		category: "single",
	},
	{
		url: "cchs-visitors-center",
		name: "CCHS Visitor's Center (In Progress)",
		text: "cchs-visitors-center.md",
		photos: [
			"https://i.ibb.co/6gS2sNN/CCHS-Dec-8-2.jpg",
			"https://i.ibb.co/hHSxg7v/CCHS-Dec-8-3.jpg",
			"https://i.ibb.co/BtZKwGc/CCHS-Dec-8-4.jpg",
			"https://i.ibb.co/7vZnJ6M/CCHS-Dec-8.jpg",
		],
		address: "Del Mar, California",
		team: [
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
			{
				name: "Chi Espenida",
				role: "Project Designer",
			},
		],
		category: "single",
	},
	{
		url: "the-art-deco",
		name: "The Art Deco (In Progress)",
		text: "the-art-deco.md",
		photos: [
			"https://i.ibb.co/Hzpg8nM/crenshaw-front-rend.jpg",
			"https://i.ibb.co/7KqSd2N/Crenshaw-Schem-Floor-Plans-2.jpg",
		],
		address: "Crenshaw District, Los Angeles, CA",
		team: [
			{
				name: "Glen Charles Salcedo",
				role: "Principal in Charge",
			},
			{
				name: "Jevon Carrington",
				role: "Project Architect/Designer",
			},
		],
		category: "retail",
	},
	{
		url: "monument",
		name: "Monument (Misc.)",
		text: "",
		photos: [
			"https://i.ibb.co/jZ18sKh/monument-back-10-03-2014.jpg",
			"https://i.ibb.co/xX07Kt3/monument-design-plan.jpg",
			"https://i.ibb.co/gTVyFc1/monument-front-10-02-2014.jpg",
		],
		address: "",
		team: [],
		category: "retail",
	},
	{
		url: "adelbert",
		name: "Adelbert (Misc.)",
		text: "",
		photos: [
			"https://i.ibb.co/Sc58Kkq/Adelbert-rend-front-1.jpg",
			"https://i.ibb.co/b6G8TGk/Adelbert-Floor-Plan.jpg",
			"https://i.ibb.co/rGdLJ5N/Adelbert-rend-front-2.jpg",
			"https://i.ibb.co/M6jTcX3/Adelbert-Rend-Front-3.jpg",
			"https://i.ibb.co/0YFzh1r/Adelbert-SCHEMATIC-FRONT-ELEVATION.jpg",
		],
		address: "",
		team: [],
		category: "retail",
	},
	{
		url: "Vista & Chula Vista Gyms",
		name: "Vista & Chula Vista Gyms (Misc.)",
		text: "",
		photos: [
			"https://i.ibb.co/94NBWtv/The-Gym-View-2-12-15-2021.jpg",
			"https://i.ibb.co/HYf5WTr/Vista-Gym-Merchs-01-07-2022.jpg",
			"https://i.ibb.co/S0fbDRD/Vista-Gym-Top-View-01-07-2022.jpg",
			"https://i.ibb.co/zX4VCBR/Vista-Gym-View1-01-06-2022.jpg",
			"https://i.ibb.co/wcDsRcR/Vista-Gym-View2-01-07-2022.jpg",
			"https://i.ibb.co/JqtyLsx/The-Gym-View-1-12-15-2021.jpg",
		],
		address: "",
		team: [],
		category: "retail",
	},
]

